(require 'ivy)
(ivy-mode 1)
(counsel-mode 1)
(setq ivy-height 30)
(global-set-key (kbd "C-@") 'counsel-M-x)
(global-set-key (kbd "C-x C-f") 'counsel-find-file)
(global-set-key (kbd "C-c t") 'counsel-recentf)
(global-set-key (kbd "C-c t") 'counsel-git-grep)
(global-set-key (kbd "C-s") 'swiper)
(global-set-key (kbd "M-r") 'counsel-recentf)
